title: "Kin's Blog"
author: "davingm"
avatar: "/images/author.jpg"
tagline: "Now or never"
url: "https://davingm.com"
description: "纯 SSG 静态博客，极简设计，专注内容与性能。"
bio: "Hi，我是 Kin。这是我使用 Inkcairn 构建的博客，尽可能减少了 JavaScript 的使用，希望能专注于写一些有趣的内容。"
commit: "121c93e"
generator: "made with nextjs v16.3.4"
nav:
  - name: "Home"
    path: ""
  - name: "Posts"
    path: "posts"
  - name: "Archive"
    path: "archive"
  - name: "About"
    path: "about"
  - name: "Projects"
    path: "projects"
  - name: "Links"
    path: "links"
social:
  github: "https://github.com/davingm"
  twitter: "https://twitter.com"
