title: "Kin's Blog"
author: "Kin"
avatar: "/images/author.jpg"
tagline: "Veni, Vidi, Vici."
url: "https://davingm.com"
description: "纯 SSG 静态博客，极简设计，专注内容与性能。"
bio: "你好，我是 Kin！这是我用 Next.js 搭建的博客，我尽量减少 JavaScript 的使用，让自己专注于写出更有趣的内容。"
commit: "121c93e"
generator: "made with nextjs v16.3.4"
nav:
  - name: "Home"
    path: ""
  - name: "Posts"
    path: "posts"
  - name: "Archive"
    path: "archive"
  - name: "About"
    path: "about"
  - name: "Projects"
    path: "projects"
  - name: "Links"
    path: "links"
social:
  github: "https://github.com/davingm"
  twitter: "https://twitter.com"
