title: "Kin's Blog"
author: "Kin"
avatar: "/images/author.jpg"
tagline: "Veni , Vidi, Vici."
url: "https://davingm.com"
description: "Blog statis pure SSG, desain minimalis, fokus pada konten dan performa."
bio: "Hai, saya Kin! Ini adalah blog yang saya bangun dengan nextjs, meminimalkan penggunaan JavaScript semaksimal mungkin, agar dapat fokus menulis konten yang menarik."
commit: "121c93e"
generator: "made with nextjs v16.3.4"
nav:
  - name: "Home"
    path: ""
  - name: "Posts"
    path: "posts"
  - name: "Archive"
    path: "archive"
  - name: "About"
    path: "about"
  - name: "Projects"
    path: "projects"
  - name: "Links"
    path: "links"
social:
  github: "https://github.com/davingm"
  twitter: "https://twitter.com"
