title: "Kin's Blog"
author: "Kin"
avatar: "/images/author.jpg"
tagline: "Veni , Vidi, Vici."
url: "https://davingm.com"
description: "Pure SSG static blog, minimal design, focused on content and performance."
bio: "Hi, I'm Kin! This is my blog built with Inkcairn, minimizing JavaScript usage as much as possible, hoping to focus on writing interesting content."
commit: "121c93e"
generator: "made with nextjs v16.3.4"
nav:
  - name: "Home"
    path: ""
  - name: "Posts"
    path: "posts"
  - name: "Archive"
    path: "archive"
  - name: "About"
    path: "about"
  - name: "Projects"
    path: "projects"
  - name: "Links"
    path: "links"
social:
  github: "https://github.com/davingm"
  twitter: "https://twitter.com"
